name: opencompass
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.10.1
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - astor==0.8.1
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - av==15.1.0
      - blake3==1.0.6
      - blessed==1.22.0
      - brotli==1.1.0
      - build==1.3.0
      - cachetools==5.5.2
      - cbor2==5.7.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpickle==3.1.1
      - cmake==4.1.0
      - colorama==0.4.6
      - comm==0.2.3
      - compressed-tensors==0.11.0
      - contourpy==1.3.2
      - cpm-kernels==1.0.11
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - datasets==3.2.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - decord==0.6.0
      - depyf==0.19.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - dotenv==0.9.9
      - einops==0.8.1
      - email-validator==2.3.0
      - et-xmlfile==2.0.0
      - evaluate==0.4.6
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.117.1
      - fastapi-cli==0.0.13
      - fastapi-cloud-cli==0.2.0
      - fastrlock==0.8.3
      - ffmpy==0.6.1
      - filelock==3.19.1
      - fire==0.7.1
      - flash-attn==2.8.3
      - fonttools==4.60.0
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - func-timeout==4.3.5
      - fuzzywuzzy==0.18.0
      - genson==1.3.0
      - gguf==0.17.1
      - google-auth==2.40.3
      - google-genai==1.38.0
      - gpustat==1.1.1
      - gradio==5.46.1
      - gradio-client==1.13.1
      - groovy==0.1.2
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.35.0
      - idna==3.10
      - imageio==2.37.0
      - immutabledict==4.2.1
      - importlib-metadata==8.7.0
      - interegular==0.3.3
      - ipdb==0.13.13
      - ipykernel==6.30.1
      - ipython==8.37.0
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.11.0
      - joblib==1.5.2
      - json-repair==0.51.0
      - json5==0.12.1
      - jsonlines==4.0.0
      - jsonpath-ng==1.7.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.9
      - langdetect==1.0.9
      - lark==1.2.2
      - latex2sympy2-extended==1.10.2
      - levenshtein==0.27.1
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - lmdeploy==0.10.0
      - lxml==6.0.2
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - math-verify==0.8.0
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - mmengine-lite==0.10.7
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.13.0
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - nvitop==1.5.3
      - omegaconf==2.3.0
      - openai==1.108.1
      - openai-harmony==0.0.4
      - opencc==1.1.9
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - orjson==3.11.3
      - outlines==1.2.5
      - outlines-core==0.2.11
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - partial-json-parser==0.2.1.1.post6
      - peft==0.14.0
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.4.0
      - ply==3.11
      - portalocker==3.2.0
      - prettytable==3.16.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pydub==0.25.1
      - pyext==0.7
      - pygments==2.19.2
      - pynvml==13.0.1
      - pyparsing==3.2.5
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-levenshtein==0.27.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.13
      - rank-bm25==0.2.2
      - rapidfuzz==3.14.1
      - ray==2.49.2
      - referencing==0.36.2
      - regex==2025.9.18
      - requests==2.32.5
      - retrying==1.4.2
      - rich==14.1.0
      - rich-toolkit==0.15.1
      - rignore==0.6.4
      - rouge==1.0.1
      - rouge-chinese==1.0.3
      - rouge-score==0.1.2
      - rpds-py==0.27.1
      - rsa==4.9.1
      - ruff==0.13.1
      - sacrebleu==2.5.1
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-learn==1.5.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentence-transformers==5.1.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.38.0
      - setproctitle==1.3.7
      - setuptools-scm==9.2.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - stack-data==0.6.3
      - starlette==0.48.0
      - sty==1.0.6
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.1.2
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - timeout-decorator==0.5.0
      - timm==1.0.20
      - tokenizers==0.21.4
      - tomli==2.2.1
      - tomlkit==0.13.3
      - torch==2.7.1+cu128
      - torchaudio==2.7.1+cu128
      - torchvision==0.22.1+cu128
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.52.4
      - tree-sitter==0.21.3
      - tree-sitter-languages==1.10.2
      - triton==3.3.1
      - typer==0.19.1
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.36.0
      - uvloop==0.21.0
      - validators==0.35.0
      - vllm==0.10.2rc3.dev325+g1c3ffdbec.d20250921
      - watchfiles==1.1.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - xgrammar==0.1.24
      - xlsxwriter==3.2.9
      - xxhash==3.5.0
      - yapf==0.43.0
      - yarl==1.20.1
      - zipp==3.23.0
